timestampsHomestead = as.matrix(read.csv(file = "blocktimes.csv"))
blocktimes= data.frame(day=as.Date(as.POSIXct(timestampsHomestead[-1,], origin="1970-01-01")), blocktime=diff(timestampsHomestead))
blocktimes <- setNames(blocktimes, c("day","blocktime"))
summary(blocktimes$blocktime)
hist(blocktimes$blocktime)
